### ISSUE TITLE
Very high memory usage with large data set

### ISSUE THREAD

**Issue by figure002** [naturalis/ai-fann-evolving#1]
The aivolver script uses a lot of memory when large data sets are used as input. This especially seems to be the case when the data set contains a lot of columns, even when there are relatively few lines.

A test with a data set of 1MB (3900 columns, 40 lines) resulted in a memory usage of 5.39GB (out of 7.7GB) and rising, resulting in the computer to become unresponsive. At the same time more than 5GB of data was written to a temporary folder, which seems a lot considering the size of the data set.

**Comment by rvosa** [comment]
I am keeping this ticket open for the time being, but I question whether it is actually justified. I personally have not read about ANNs with more than 1,000 inputs (or thereabouts), and I would expect that correct classification depends much more on actually creating features that capture the similarities within classes and the differences between them. The fewer inputs you need for that, the better.
