### ISSUE TITLE
Setting `fraction` option to 1.0 fails

### ISSUE THREAD

**Issue by figure002** [naturalis/ai-fann-evolving#5]
When the training data is already split into separate test data, you'll want to set `fraction` to 1.0 so that all data in the data set is used for training. In this case, the training data itself should be used as test data. Currently the script will fail when `fraction` is set to 1.0.

**Comment by rvosa** [comment]
Done: as of commit 8719add, `--fraction` can now be set to 1, so that train and test data are identical.
